export const ECRVS_MAIN_MENU_CONTRIBUTION_KEY = 'ecrvs.MainMenu';

export const RIGHT_HERA_SUBSCRIPTIONS_SEARCH = 124000
export const RIGHT_HERA_SUBSCRIPTIONS_CREATE = 124001
export const RIGHT_HERA_SUBSCRIPTIONS_DELETE = 124002
export const RIGHT_HERA_NOTIFICATIONS_SEARCH = 125000

export const ROWS_PER_PAGE_OPTIONS = [10, 20, 50, 100];
export const DEFAULT_PAGE_SIZE = 10;

export const HERA_NOTIFICATIONS_STATUS_RECEIVED = "RECEIVED"
export const HERA_NOTIFICATIONS_STATUS_INVALID = "INVALID"
export const HERA_NOTIFICATIONS_STATUS_SUCCESS = "SUCCESS"
export const HERA_NOTIFICATIONS_STATUS_ERROR = "ERROR"
export const HERA_NOTIFICATIONS_STATUSES = [
    HERA_NOTIFICATIONS_STATUS_RECEIVED,
    HERA_NOTIFICATIONS_STATUS_INVALID,
    HERA_NOTIFICATIONS_STATUS_SUCCESS,
    HERA_NOTIFICATIONS_STATUS_ERROR
]

export const HERA_NOTIFICATIONS_OPERATION_CREATE = "CREATE"
export const HERA_NOTIFICATIONS_OPERATION_UPDATE = "UPDATE"
export const HERA_NOTIFICATIONS_OPERATION_DELETE = "DELETE"
export const HERA_NOTIFICATIONS_OPERATIONS = [
    HERA_NOTIFICATIONS_OPERATION_CREATE,
    HERA_NOTIFICATIONS_OPERATION_UPDATE,
    HERA_NOTIFICATIONS_OPERATION_DELETE,
]

export const HERA_NOTIFICATIONS_TOPIC_LIFE = "LifeEventTopic"
export const HERA_NOTIFICATIONS_TOPIC_LOCATION = "LocationEventTopic"
export const HERA_NOTIFICATIONS_TOPICS = [
    HERA_NOTIFICATIONS_TOPIC_LIFE,
    HERA_NOTIFICATIONS_TOPIC_LOCATION,
]
export const HERA_SUBSCRIPTIONS_STATUS_ACTIVE = "true"
export const HERA_SUBSCRIPTIONS_STATUS_DELETED = "false"
export const HERA_SUBSCRIPTIONS_STATUSES = [
    HERA_SUBSCRIPTIONS_STATUS_ACTIVE,
    HERA_SUBSCRIPTIONS_STATUS_DELETED
]
